services:
  discovery:
    image: discovery
    container_name: discovery
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8761:8761
    environment:
      - APP_PROFILE=prod
      - DISCOVERY_SERVICE_PORT=8761
      - CONFIG_URI=http://config:8888
    networks:
      - online-shop-network

networks:
  online-shop-network:
    external: true
