server:
  port: ${PRODUCT_SERVICE_PORT:8082}
spring:
  application:
    name: product
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      enabled: true
      allow-override: true
      uri: ${CONFIG_URI:http://localhost:8888}
      name: product
      profile: ${APP_PROFILE:dev}
      fail-fast: true
