spring:
  application:
    name: discovery-service
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      enabled: true
      allow-override: true
      uri: ${CONFIG_URI:http://localhost:8888}
      name: discovery
      profile: ${APP_PROFILE:dev}
      fail-fast: true

server:
  port: ${DISCOVERY_SERVICE_PORT:8761}
