server:
  port: ${GATEWAY_SERVICE_PORT:8070}
spring:
  application:
    name: gateway
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      enabled: true
      allow-override: true
      uri: ${CONFIG_URI:http://localhost:8888}
      name: gateway
      profile: ${APP_PROFILE:dev}
      fail-fast: true
