spring:
  application:
    name: inventory
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      enabled: true
      allow-override: true
      uri: ${CONFIG_URI:http://localhost:8888}
      name: inventory
      profile: ${APP_PROFILE:dev}
      fail-fast: true
server:
  port: ${INVENTORY_SERVICE_PORT:8086}
