services:
  user_db:
    container_name: user_db
    image: postgres:15
    volumes:
      - user_db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    ports:
      - '5440:5432'
    networks:
      - online-shop-network

  keycloak:
    container_name: keycloak
    hostname: keycloak
    image: quay.io/keycloak/keycloak:24.0
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://user_db/user_db
      KC_DB_USERNAME: user
      KC_DB_PASSWORD: user
    ports:
      - '9080:8080'
    command:
      - start-dev
    depends_on:
      - user_db
    networks:
      - online-shop-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_user
    depends_on:
      - user_db
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin_user:/var/lib/pgadmin
    ports:
      - '5050:80'
    networks:
      - online-shop-network

volumes:
  user_db:
  pgadmin_user:

networks:
  online-shop-network:
    external: true
